################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../middleware/u8glib/fntsrc/u8g_font_04b_03.c \
../middleware/u8glib/fntsrc/u8g_font_04b_03b.c \
../middleware/u8glib/fntsrc/u8g_font_04b_03bn.c \
../middleware/u8glib/fntsrc/u8g_font_04b_03br.c \
../middleware/u8glib/fntsrc/u8g_font_04b_03n.c \
../middleware/u8glib/fntsrc/u8g_font_04b_03r.c \
../middleware/u8glib/fntsrc/u8g_font_04b_24.c \
../middleware/u8glib/fntsrc/u8g_font_04b_24n.c \
../middleware/u8glib/fntsrc/u8g_font_04b_24r.c \
../middleware/u8glib/fntsrc/u8g_font_10x20.c \
../middleware/u8glib/fntsrc/u8g_font_10x20_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_10x20_75r.c \
../middleware/u8glib/fntsrc/u8g_font_10x20_78_79.c \
../middleware/u8glib/fntsrc/u8g_font_10x20r.c \
../middleware/u8glib/fntsrc/u8g_font_4x6.c \
../middleware/u8glib/fntsrc/u8g_font_4x6r.c \
../middleware/u8glib/fntsrc/u8g_font_5x7.c \
../middleware/u8glib/fntsrc/u8g_font_5x7r.c \
../middleware/u8glib/fntsrc/u8g_font_5x8.c \
../middleware/u8glib/fntsrc/u8g_font_5x8r.c \
../middleware/u8glib/fntsrc/u8g_font_6x10.c \
../middleware/u8glib/fntsrc/u8g_font_6x10r.c \
../middleware/u8glib/fntsrc/u8g_font_6x12.c \
../middleware/u8glib/fntsrc/u8g_font_6x12_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_6x12_75r.c \
../middleware/u8glib/fntsrc/u8g_font_6x12_78_79.c \
../middleware/u8glib/fntsrc/u8g_font_6x12r.c \
../middleware/u8glib/fntsrc/u8g_font_6x13.c \
../middleware/u8glib/fntsrc/u8g_font_6x13B.c \
../middleware/u8glib/fntsrc/u8g_font_6x13Br.c \
../middleware/u8glib/fntsrc/u8g_font_6x13O.c \
../middleware/u8glib/fntsrc/u8g_font_6x13Or.c \
../middleware/u8glib/fntsrc/u8g_font_6x13_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_6x13_75r.c \
../middleware/u8glib/fntsrc/u8g_font_6x13_78_79.c \
../middleware/u8glib/fntsrc/u8g_font_6x13r.c \
../middleware/u8glib/fntsrc/u8g_font_7x13.c \
../middleware/u8glib/fntsrc/u8g_font_7x13B.c \
../middleware/u8glib/fntsrc/u8g_font_7x13Br.c \
../middleware/u8glib/fntsrc/u8g_font_7x13O.c \
../middleware/u8glib/fntsrc/u8g_font_7x13Or.c \
../middleware/u8glib/fntsrc/u8g_font_7x13_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_7x13_75r.c \
../middleware/u8glib/fntsrc/u8g_font_7x13r.c \
../middleware/u8glib/fntsrc/u8g_font_7x14.c \
../middleware/u8glib/fntsrc/u8g_font_7x14B.c \
../middleware/u8glib/fntsrc/u8g_font_7x14Br.c \
../middleware/u8glib/fntsrc/u8g_font_7x14r.c \
../middleware/u8glib/fntsrc/u8g_font_8x13.c \
../middleware/u8glib/fntsrc/u8g_font_8x13B.c \
../middleware/u8glib/fntsrc/u8g_font_8x13Br.c \
../middleware/u8glib/fntsrc/u8g_font_8x13O.c \
../middleware/u8glib/fntsrc/u8g_font_8x13Or.c \
../middleware/u8glib/fntsrc/u8g_font_8x13_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_8x13_75r.c \
../middleware/u8glib/fntsrc/u8g_font_8x13r.c \
../middleware/u8glib/fntsrc/u8g_font_9x15.c \
../middleware/u8glib/fntsrc/u8g_font_9x15B.c \
../middleware/u8glib/fntsrc/u8g_font_9x15Br.c \
../middleware/u8glib/fntsrc/u8g_font_9x15_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_9x15_75r.c \
../middleware/u8glib/fntsrc/u8g_font_9x15_78_79.c \
../middleware/u8glib/fntsrc/u8g_font_9x15r.c \
../middleware/u8glib/fntsrc/u8g_font_9x18.c \
../middleware/u8glib/fntsrc/u8g_font_9x18B.c \
../middleware/u8glib/fntsrc/u8g_font_9x18Br.c \
../middleware/u8glib/fntsrc/u8g_font_9x18_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_9x18_75r.c \
../middleware/u8glib/fntsrc/u8g_font_9x18_78_79.c \
../middleware/u8glib/fntsrc/u8g_font_9x18r.c \
../middleware/u8glib/fntsrc/u8g_font_baby.c \
../middleware/u8glib/fntsrc/u8g_font_babyn.c \
../middleware/u8glib/fntsrc/u8g_font_babyr.c \
../middleware/u8glib/fntsrc/u8g_font_blipfest_07.c \
../middleware/u8glib/fntsrc/u8g_font_blipfest_07n.c \
../middleware/u8glib/fntsrc/u8g_font_blipfest_07r.c \
../middleware/u8glib/fntsrc/u8g_font_chikita.c \
../middleware/u8glib/fntsrc/u8g_font_chikitan.c \
../middleware/u8glib/fntsrc/u8g_font_chikitar.c \
../middleware/u8glib/fntsrc/u8g_font_courb08.c \
../middleware/u8glib/fntsrc/u8g_font_courb08r.c \
../middleware/u8glib/fntsrc/u8g_font_courb10.c \
../middleware/u8glib/fntsrc/u8g_font_courb10r.c \
../middleware/u8glib/fntsrc/u8g_font_courb12.c \
../middleware/u8glib/fntsrc/u8g_font_courb12r.c \
../middleware/u8glib/fntsrc/u8g_font_courb14.c \
../middleware/u8glib/fntsrc/u8g_font_courb14r.c \
../middleware/u8glib/fntsrc/u8g_font_courb18.c \
../middleware/u8glib/fntsrc/u8g_font_courb18r.c \
../middleware/u8glib/fntsrc/u8g_font_courb24.c \
../middleware/u8glib/fntsrc/u8g_font_courb24r.c \
../middleware/u8glib/fntsrc/u8g_font_courb4n.c \
../middleware/u8glib/fntsrc/u8g_font_courr08.c \
../middleware/u8glib/fntsrc/u8g_font_courr08r.c \
../middleware/u8glib/fntsrc/u8g_font_courr10.c \
../middleware/u8glib/fntsrc/u8g_font_courr10r.c \
../middleware/u8glib/fntsrc/u8g_font_courr12.c \
../middleware/u8glib/fntsrc/u8g_font_courr12r.c \
../middleware/u8glib/fntsrc/u8g_font_courr14.c \
../middleware/u8glib/fntsrc/u8g_font_courr14r.c \
../middleware/u8glib/fntsrc/u8g_font_courr18.c \
../middleware/u8glib/fntsrc/u8g_font_courr18r.c \
../middleware/u8glib/fntsrc/u8g_font_courr24.c \
../middleware/u8glib/fntsrc/u8g_font_courr24n.c \
../middleware/u8glib/fntsrc/u8g_font_courr24r.c \
../middleware/u8glib/fntsrc/u8g_font_cu12.c \
../middleware/u8glib/fntsrc/u8g_font_cu12_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_cu12_75r.c \
../middleware/u8glib/fntsrc/u8g_font_cursor.c \
../middleware/u8glib/fntsrc/u8g_font_cursorr.c \
../middleware/u8glib/fntsrc/u8g_font_fixed_v0.c \
../middleware/u8glib/fntsrc/u8g_font_fixed_v0n.c \
../middleware/u8glib/fntsrc/u8g_font_fixed_v0r.c \
../middleware/u8glib/fntsrc/u8g_font_freedoomr10r.c \
../middleware/u8glib/fntsrc/u8g_font_freedoomr25n.c \
../middleware/u8glib/fntsrc/u8g_font_fub11.c \
../middleware/u8glib/fntsrc/u8g_font_fub11n.c \
../middleware/u8glib/fntsrc/u8g_font_fub11r.c \
../middleware/u8glib/fntsrc/u8g_font_fub14.c \
../middleware/u8glib/fntsrc/u8g_font_fub14n.c \
../middleware/u8glib/fntsrc/u8g_font_fub14r.c \
../middleware/u8glib/fntsrc/u8g_font_fub17.c \
../middleware/u8glib/fntsrc/u8g_font_fub17n.c \
../middleware/u8glib/fntsrc/u8g_font_fub17r.c \
../middleware/u8glib/fntsrc/u8g_font_fub20.c \
../middleware/u8glib/fntsrc/u8g_font_fub20n.c \
../middleware/u8glib/fntsrc/u8g_font_fub20r.c \
../middleware/u8glib/fntsrc/u8g_font_fub25.c \
../middleware/u8glib/fntsrc/u8g_font_fub25n.c \
../middleware/u8glib/fntsrc/u8g_font_fub25r.c \
../middleware/u8glib/fntsrc/u8g_font_fub30.c \
../middleware/u8glib/fntsrc/u8g_font_fub30n.c \
../middleware/u8glib/fntsrc/u8g_font_fub30r.c \
../middleware/u8glib/fntsrc/u8g_font_fub35n.c \
../middleware/u8glib/fntsrc/u8g_font_fub42n.c \
../middleware/u8glib/fntsrc/u8g_font_fub49n.c \
../middleware/u8glib/fntsrc/u8g_font_fur11.c \
../middleware/u8glib/fntsrc/u8g_font_fur11n.c \
../middleware/u8glib/fntsrc/u8g_font_fur11r.c \
../middleware/u8glib/fntsrc/u8g_font_fur14.c \
../middleware/u8glib/fntsrc/u8g_font_fur14n.c \
../middleware/u8glib/fntsrc/u8g_font_fur14r.c \
../middleware/u8glib/fntsrc/u8g_font_fur17.c \
../middleware/u8glib/fntsrc/u8g_font_fur17n.c \
../middleware/u8glib/fntsrc/u8g_font_fur17r.c \
../middleware/u8glib/fntsrc/u8g_font_fur20.c \
../middleware/u8glib/fntsrc/u8g_font_fur20n.c \
../middleware/u8glib/fntsrc/u8g_font_fur20r.c \
../middleware/u8glib/fntsrc/u8g_font_fur25.c \
../middleware/u8glib/fntsrc/u8g_font_fur25n.c \
../middleware/u8glib/fntsrc/u8g_font_fur25r.c \
../middleware/u8glib/fntsrc/u8g_font_fur30.c \
../middleware/u8glib/fntsrc/u8g_font_fur30n.c \
../middleware/u8glib/fntsrc/u8g_font_fur30r.c \
../middleware/u8glib/fntsrc/u8g_font_fur35n.c \
../middleware/u8glib/fntsrc/u8g_font_fur42n.c \
../middleware/u8glib/fntsrc/u8g_font_fur49n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb11.c \
../middleware/u8glib/fntsrc/u8g_font_gdb11n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb11r.c \
../middleware/u8glib/fntsrc/u8g_font_gdb12.c \
../middleware/u8glib/fntsrc/u8g_font_gdb12n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb12r.c \
../middleware/u8glib/fntsrc/u8g_font_gdb14.c \
../middleware/u8glib/fntsrc/u8g_font_gdb14n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb14r.c \
../middleware/u8glib/fntsrc/u8g_font_gdb17.c \
../middleware/u8glib/fntsrc/u8g_font_gdb17n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb17r.c \
../middleware/u8glib/fntsrc/u8g_font_gdb20.c \
../middleware/u8glib/fntsrc/u8g_font_gdb20n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb20r.c \
../middleware/u8glib/fntsrc/u8g_font_gdb25.c \
../middleware/u8glib/fntsrc/u8g_font_gdb25n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb25r.c \
../middleware/u8glib/fntsrc/u8g_font_gdb30.c \
../middleware/u8glib/fntsrc/u8g_font_gdb30n.c \
../middleware/u8glib/fntsrc/u8g_font_gdb30r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr10.c \
../middleware/u8glib/fntsrc/u8g_font_gdr10n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr10r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr11.c \
../middleware/u8glib/fntsrc/u8g_font_gdr11n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr11r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr12.c \
../middleware/u8glib/fntsrc/u8g_font_gdr12n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr12r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr14.c \
../middleware/u8glib/fntsrc/u8g_font_gdr14n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr14r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr17.c \
../middleware/u8glib/fntsrc/u8g_font_gdr17n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr17r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr20.c \
../middleware/u8glib/fntsrc/u8g_font_gdr20n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr20r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr25.c \
../middleware/u8glib/fntsrc/u8g_font_gdr25n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr25r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr30.c \
../middleware/u8glib/fntsrc/u8g_font_gdr30n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr30r.c \
../middleware/u8glib/fntsrc/u8g_font_gdr9.c \
../middleware/u8glib/fntsrc/u8g_font_gdr9n.c \
../middleware/u8glib/fntsrc/u8g_font_gdr9r.c \
../middleware/u8glib/fntsrc/u8g_font_helvb08.c \
../middleware/u8glib/fntsrc/u8g_font_helvb08n.c \
../middleware/u8glib/fntsrc/u8g_font_helvb08r.c \
../middleware/u8glib/fntsrc/u8g_font_helvb10.c \
../middleware/u8glib/fntsrc/u8g_font_helvb10n.c \
../middleware/u8glib/fntsrc/u8g_font_helvb10r.c \
../middleware/u8glib/fntsrc/u8g_font_helvb12.c \
../middleware/u8glib/fntsrc/u8g_font_helvb12n.c \
../middleware/u8glib/fntsrc/u8g_font_helvb12r.c \
../middleware/u8glib/fntsrc/u8g_font_helvb14.c \
../middleware/u8glib/fntsrc/u8g_font_helvb14n.c \
../middleware/u8glib/fntsrc/u8g_font_helvb14r.c \
../middleware/u8glib/fntsrc/u8g_font_helvb18.c \
../middleware/u8glib/fntsrc/u8g_font_helvb18n.c \
../middleware/u8glib/fntsrc/u8g_font_helvb18r.c \
../middleware/u8glib/fntsrc/u8g_font_helvb24.c \
../middleware/u8glib/fntsrc/u8g_font_helvb24n.c \
../middleware/u8glib/fntsrc/u8g_font_helvb24r.c \
../middleware/u8glib/fntsrc/u8g_font_helvr08.c \
../middleware/u8glib/fntsrc/u8g_font_helvr08r.c \
../middleware/u8glib/fntsrc/u8g_font_helvr10.c \
../middleware/u8glib/fntsrc/u8g_font_helvr10r.c \
../middleware/u8glib/fntsrc/u8g_font_helvr12.c \
../middleware/u8glib/fntsrc/u8g_font_helvr12r.c \
../middleware/u8glib/fntsrc/u8g_font_helvr14.c \
../middleware/u8glib/fntsrc/u8g_font_helvr14r.c \
../middleware/u8glib/fntsrc/u8g_font_helvr18.c \
../middleware/u8glib/fntsrc/u8g_font_helvr18r.c \
../middleware/u8glib/fntsrc/u8g_font_helvr24.c \
../middleware/u8glib/fntsrc/u8g_font_helvr24n.c \
../middleware/u8glib/fntsrc/u8g_font_helvr24r.c \
../middleware/u8glib/fntsrc/u8g_font_lucasfont_alternate.c \
../middleware/u8glib/fntsrc/u8g_font_lucasfont_alternaten.c \
../middleware/u8glib/fntsrc/u8g_font_lucasfont_alternater.c \
../middleware/u8glib/fntsrc/u8g_font_m2icon_5.c \
../middleware/u8glib/fntsrc/u8g_font_m2icon_7.c \
../middleware/u8glib/fntsrc/u8g_font_m2icon_9.c \
../middleware/u8glib/fntsrc/u8g_font_micro.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb08.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb08r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb10.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb10r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb12.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb12r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb14.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb14r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb18.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb18r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb24.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb24n.c \
../middleware/u8glib/fntsrc/u8g_font_ncenb24r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr08.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr08r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr10.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr10r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr12.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr12r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr14.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr14r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr18.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr18r.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr24.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr24n.c \
../middleware/u8glib/fntsrc/u8g_font_ncenr24r.c \
../middleware/u8glib/fntsrc/u8g_font_orgv01.c \
../middleware/u8glib/fntsrc/u8g_font_orgv01n.c \
../middleware/u8glib/fntsrc/u8g_font_orgv01r.c \
../middleware/u8glib/fntsrc/u8g_font_osb18.c \
../middleware/u8glib/fntsrc/u8g_font_osb18n.c \
../middleware/u8glib/fntsrc/u8g_font_osb18r.c \
../middleware/u8glib/fntsrc/u8g_font_osb21.c \
../middleware/u8glib/fntsrc/u8g_font_osb21n.c \
../middleware/u8glib/fntsrc/u8g_font_osb21r.c \
../middleware/u8glib/fntsrc/u8g_font_osb26.c \
../middleware/u8glib/fntsrc/u8g_font_osb26n.c \
../middleware/u8glib/fntsrc/u8g_font_osb26r.c \
../middleware/u8glib/fntsrc/u8g_font_osb29.c \
../middleware/u8glib/fntsrc/u8g_font_osb29n.c \
../middleware/u8glib/fntsrc/u8g_font_osb29r.c \
../middleware/u8glib/fntsrc/u8g_font_osb35.c \
../middleware/u8glib/fntsrc/u8g_font_osb35n.c \
../middleware/u8glib/fntsrc/u8g_font_osb35r.c \
../middleware/u8glib/fntsrc/u8g_font_osr18.c \
../middleware/u8glib/fntsrc/u8g_font_osr18n.c \
../middleware/u8glib/fntsrc/u8g_font_osr18r.c \
../middleware/u8glib/fntsrc/u8g_font_osr21.c \
../middleware/u8glib/fntsrc/u8g_font_osr21n.c \
../middleware/u8glib/fntsrc/u8g_font_osr21r.c \
../middleware/u8glib/fntsrc/u8g_font_osr26.c \
../middleware/u8glib/fntsrc/u8g_font_osr26n.c \
../middleware/u8glib/fntsrc/u8g_font_osr26r.c \
../middleware/u8glib/fntsrc/u8g_font_osr29.c \
../middleware/u8glib/fntsrc/u8g_font_osr29n.c \
../middleware/u8glib/fntsrc/u8g_font_osr29r.c \
../middleware/u8glib/fntsrc/u8g_font_osr35.c \
../middleware/u8glib/fntsrc/u8g_font_osr35n.c \
../middleware/u8glib/fntsrc/u8g_font_osr35r.c \
../middleware/u8glib/fntsrc/u8g_font_p01type.c \
../middleware/u8glib/fntsrc/u8g_font_p01typen.c \
../middleware/u8glib/fntsrc/u8g_font_p01typer.c \
../middleware/u8glib/fntsrc/u8g_font_pixelle_micro.c \
../middleware/u8glib/fntsrc/u8g_font_pixelle_micron.c \
../middleware/u8glib/fntsrc/u8g_font_pixelle_micror.c \
../middleware/u8glib/fntsrc/u8g_font_profont10.c \
../middleware/u8glib/fntsrc/u8g_font_profont10r.c \
../middleware/u8glib/fntsrc/u8g_font_profont11.c \
../middleware/u8glib/fntsrc/u8g_font_profont11r.c \
../middleware/u8glib/fntsrc/u8g_font_profont12.c \
../middleware/u8glib/fntsrc/u8g_font_profont12r.c \
../middleware/u8glib/fntsrc/u8g_font_profont15.c \
../middleware/u8glib/fntsrc/u8g_font_profont15r.c \
../middleware/u8glib/fntsrc/u8g_font_profont17.c \
../middleware/u8glib/fntsrc/u8g_font_profont17r.c \
../middleware/u8glib/fntsrc/u8g_font_profont22.c \
../middleware/u8glib/fntsrc/u8g_font_profont22r.c \
../middleware/u8glib/fntsrc/u8g_font_profont29.c \
../middleware/u8glib/fntsrc/u8g_font_profont29r.c \
../middleware/u8glib/fntsrc/u8g_font_robot_de_niro.c \
../middleware/u8glib/fntsrc/u8g_font_robot_de_niron.c \
../middleware/u8glib/fntsrc/u8g_font_robot_de_niror.c \
../middleware/u8glib/fntsrc/u8g_font_symb08.c \
../middleware/u8glib/fntsrc/u8g_font_symb08r.c \
../middleware/u8glib/fntsrc/u8g_font_symb10.c \
../middleware/u8glib/fntsrc/u8g_font_symb10r.c \
../middleware/u8glib/fntsrc/u8g_font_symb12.c \
../middleware/u8glib/fntsrc/u8g_font_symb12r.c \
../middleware/u8glib/fntsrc/u8g_font_symb14.c \
../middleware/u8glib/fntsrc/u8g_font_symb14r.c \
../middleware/u8glib/fntsrc/u8g_font_symb18.c \
../middleware/u8glib/fntsrc/u8g_font_symb18r.c \
../middleware/u8glib/fntsrc/u8g_font_symb24.c \
../middleware/u8glib/fntsrc/u8g_font_symb24r.c \
../middleware/u8glib/fntsrc/u8g_font_timb08.c \
../middleware/u8glib/fntsrc/u8g_font_timb08r.c \
../middleware/u8glib/fntsrc/u8g_font_timb10.c \
../middleware/u8glib/fntsrc/u8g_font_timb10r.c \
../middleware/u8glib/fntsrc/u8g_font_timb12.c \
../middleware/u8glib/fntsrc/u8g_font_timb12r.c \
../middleware/u8glib/fntsrc/u8g_font_timb14.c \
../middleware/u8glib/fntsrc/u8g_font_timb14r.c \
../middleware/u8glib/fntsrc/u8g_font_timb18.c \
../middleware/u8glib/fntsrc/u8g_font_timb18r.c \
../middleware/u8glib/fntsrc/u8g_font_timb24.c \
../middleware/u8glib/fntsrc/u8g_font_timb24n.c \
../middleware/u8glib/fntsrc/u8g_font_timb24r.c \
../middleware/u8glib/fntsrc/u8g_font_timr08.c \
../middleware/u8glib/fntsrc/u8g_font_timr08r.c \
../middleware/u8glib/fntsrc/u8g_font_timr10.c \
../middleware/u8glib/fntsrc/u8g_font_timr10r.c \
../middleware/u8glib/fntsrc/u8g_font_timr12.c \
../middleware/u8glib/fntsrc/u8g_font_timr12r.c \
../middleware/u8glib/fntsrc/u8g_font_timr14.c \
../middleware/u8glib/fntsrc/u8g_font_timr14r.c \
../middleware/u8glib/fntsrc/u8g_font_timr18.c \
../middleware/u8glib/fntsrc/u8g_font_timr18r.c \
../middleware/u8glib/fntsrc/u8g_font_timr24.c \
../middleware/u8glib/fntsrc/u8g_font_timr24n.c \
../middleware/u8glib/fntsrc/u8g_font_timr24r.c \
../middleware/u8glib/fntsrc/u8g_font_tpss.c \
../middleware/u8glib/fntsrc/u8g_font_tpssb.c \
../middleware/u8glib/fntsrc/u8g_font_tpssbn.c \
../middleware/u8glib/fntsrc/u8g_font_tpssbr.c \
../middleware/u8glib/fntsrc/u8g_font_tpssn.c \
../middleware/u8glib/fntsrc/u8g_font_tpssr.c \
../middleware/u8glib/fntsrc/u8g_font_trixel_square.c \
../middleware/u8glib/fntsrc/u8g_font_trixel_squaren.c \
../middleware/u8glib/fntsrc/u8g_font_trixel_squarer.c \
../middleware/u8glib/fntsrc/u8g_font_u8glib_4.c \
../middleware/u8glib/fntsrc/u8g_font_u8glib_4r.c \
../middleware/u8glib/fntsrc/u8g_font_unifont.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_0_8.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_12_13.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_18_19.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_2_3.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_4_5.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_67_75.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_72_73.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_75r.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_76.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_77.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_78_79.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_86.c \
../middleware/u8glib/fntsrc/u8g_font_unifont_8_9.c \
../middleware/u8glib/fntsrc/u8g_font_unifontr.c 

OBJS += \
./middleware/u8glib/fntsrc/u8g_font_04b_03.o \
./middleware/u8glib/fntsrc/u8g_font_04b_03b.o \
./middleware/u8glib/fntsrc/u8g_font_04b_03bn.o \
./middleware/u8glib/fntsrc/u8g_font_04b_03br.o \
./middleware/u8glib/fntsrc/u8g_font_04b_03n.o \
./middleware/u8glib/fntsrc/u8g_font_04b_03r.o \
./middleware/u8glib/fntsrc/u8g_font_04b_24.o \
./middleware/u8glib/fntsrc/u8g_font_04b_24n.o \
./middleware/u8glib/fntsrc/u8g_font_04b_24r.o \
./middleware/u8glib/fntsrc/u8g_font_10x20.o \
./middleware/u8glib/fntsrc/u8g_font_10x20_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_10x20_75r.o \
./middleware/u8glib/fntsrc/u8g_font_10x20_78_79.o \
./middleware/u8glib/fntsrc/u8g_font_10x20r.o \
./middleware/u8glib/fntsrc/u8g_font_4x6.o \
./middleware/u8glib/fntsrc/u8g_font_4x6r.o \
./middleware/u8glib/fntsrc/u8g_font_5x7.o \
./middleware/u8glib/fntsrc/u8g_font_5x7r.o \
./middleware/u8glib/fntsrc/u8g_font_5x8.o \
./middleware/u8glib/fntsrc/u8g_font_5x8r.o \
./middleware/u8glib/fntsrc/u8g_font_6x10.o \
./middleware/u8glib/fntsrc/u8g_font_6x10r.o \
./middleware/u8glib/fntsrc/u8g_font_6x12.o \
./middleware/u8glib/fntsrc/u8g_font_6x12_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_6x12_75r.o \
./middleware/u8glib/fntsrc/u8g_font_6x12_78_79.o \
./middleware/u8glib/fntsrc/u8g_font_6x12r.o \
./middleware/u8glib/fntsrc/u8g_font_6x13.o \
./middleware/u8glib/fntsrc/u8g_font_6x13B.o \
./middleware/u8glib/fntsrc/u8g_font_6x13Br.o \
./middleware/u8glib/fntsrc/u8g_font_6x13O.o \
./middleware/u8glib/fntsrc/u8g_font_6x13Or.o \
./middleware/u8glib/fntsrc/u8g_font_6x13_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_6x13_75r.o \
./middleware/u8glib/fntsrc/u8g_font_6x13_78_79.o \
./middleware/u8glib/fntsrc/u8g_font_6x13r.o \
./middleware/u8glib/fntsrc/u8g_font_7x13.o \
./middleware/u8glib/fntsrc/u8g_font_7x13B.o \
./middleware/u8glib/fntsrc/u8g_font_7x13Br.o \
./middleware/u8glib/fntsrc/u8g_font_7x13O.o \
./middleware/u8glib/fntsrc/u8g_font_7x13Or.o \
./middleware/u8glib/fntsrc/u8g_font_7x13_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_7x13_75r.o \
./middleware/u8glib/fntsrc/u8g_font_7x13r.o \
./middleware/u8glib/fntsrc/u8g_font_7x14.o \
./middleware/u8glib/fntsrc/u8g_font_7x14B.o \
./middleware/u8glib/fntsrc/u8g_font_7x14Br.o \
./middleware/u8glib/fntsrc/u8g_font_7x14r.o \
./middleware/u8glib/fntsrc/u8g_font_8x13.o \
./middleware/u8glib/fntsrc/u8g_font_8x13B.o \
./middleware/u8glib/fntsrc/u8g_font_8x13Br.o \
./middleware/u8glib/fntsrc/u8g_font_8x13O.o \
./middleware/u8glib/fntsrc/u8g_font_8x13Or.o \
./middleware/u8glib/fntsrc/u8g_font_8x13_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_8x13_75r.o \
./middleware/u8glib/fntsrc/u8g_font_8x13r.o \
./middleware/u8glib/fntsrc/u8g_font_9x15.o \
./middleware/u8glib/fntsrc/u8g_font_9x15B.o \
./middleware/u8glib/fntsrc/u8g_font_9x15Br.o \
./middleware/u8glib/fntsrc/u8g_font_9x15_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_9x15_75r.o \
./middleware/u8glib/fntsrc/u8g_font_9x15_78_79.o \
./middleware/u8glib/fntsrc/u8g_font_9x15r.o \
./middleware/u8glib/fntsrc/u8g_font_9x18.o \
./middleware/u8glib/fntsrc/u8g_font_9x18B.o \
./middleware/u8glib/fntsrc/u8g_font_9x18Br.o \
./middleware/u8glib/fntsrc/u8g_font_9x18_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_9x18_75r.o \
./middleware/u8glib/fntsrc/u8g_font_9x18_78_79.o \
./middleware/u8glib/fntsrc/u8g_font_9x18r.o \
./middleware/u8glib/fntsrc/u8g_font_baby.o \
./middleware/u8glib/fntsrc/u8g_font_babyn.o \
./middleware/u8glib/fntsrc/u8g_font_babyr.o \
./middleware/u8glib/fntsrc/u8g_font_blipfest_07.o \
./middleware/u8glib/fntsrc/u8g_font_blipfest_07n.o \
./middleware/u8glib/fntsrc/u8g_font_blipfest_07r.o \
./middleware/u8glib/fntsrc/u8g_font_chikita.o \
./middleware/u8glib/fntsrc/u8g_font_chikitan.o \
./middleware/u8glib/fntsrc/u8g_font_chikitar.o \
./middleware/u8glib/fntsrc/u8g_font_courb08.o \
./middleware/u8glib/fntsrc/u8g_font_courb08r.o \
./middleware/u8glib/fntsrc/u8g_font_courb10.o \
./middleware/u8glib/fntsrc/u8g_font_courb10r.o \
./middleware/u8glib/fntsrc/u8g_font_courb12.o \
./middleware/u8glib/fntsrc/u8g_font_courb12r.o \
./middleware/u8glib/fntsrc/u8g_font_courb14.o \
./middleware/u8glib/fntsrc/u8g_font_courb14r.o \
./middleware/u8glib/fntsrc/u8g_font_courb18.o \
./middleware/u8glib/fntsrc/u8g_font_courb18r.o \
./middleware/u8glib/fntsrc/u8g_font_courb24.o \
./middleware/u8glib/fntsrc/u8g_font_courb24r.o \
./middleware/u8glib/fntsrc/u8g_font_courb4n.o \
./middleware/u8glib/fntsrc/u8g_font_courr08.o \
./middleware/u8glib/fntsrc/u8g_font_courr08r.o \
./middleware/u8glib/fntsrc/u8g_font_courr10.o \
./middleware/u8glib/fntsrc/u8g_font_courr10r.o \
./middleware/u8glib/fntsrc/u8g_font_courr12.o \
./middleware/u8glib/fntsrc/u8g_font_courr12r.o \
./middleware/u8glib/fntsrc/u8g_font_courr14.o \
./middleware/u8glib/fntsrc/u8g_font_courr14r.o \
./middleware/u8glib/fntsrc/u8g_font_courr18.o \
./middleware/u8glib/fntsrc/u8g_font_courr18r.o \
./middleware/u8glib/fntsrc/u8g_font_courr24.o \
./middleware/u8glib/fntsrc/u8g_font_courr24n.o \
./middleware/u8glib/fntsrc/u8g_font_courr24r.o \
./middleware/u8glib/fntsrc/u8g_font_cu12.o \
./middleware/u8glib/fntsrc/u8g_font_cu12_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_cu12_75r.o \
./middleware/u8glib/fntsrc/u8g_font_cursor.o \
./middleware/u8glib/fntsrc/u8g_font_cursorr.o \
./middleware/u8glib/fntsrc/u8g_font_fixed_v0.o \
./middleware/u8glib/fntsrc/u8g_font_fixed_v0n.o \
./middleware/u8glib/fntsrc/u8g_font_fixed_v0r.o \
./middleware/u8glib/fntsrc/u8g_font_freedoomr10r.o \
./middleware/u8glib/fntsrc/u8g_font_freedoomr25n.o \
./middleware/u8glib/fntsrc/u8g_font_fub11.o \
./middleware/u8glib/fntsrc/u8g_font_fub11n.o \
./middleware/u8glib/fntsrc/u8g_font_fub11r.o \
./middleware/u8glib/fntsrc/u8g_font_fub14.o \
./middleware/u8glib/fntsrc/u8g_font_fub14n.o \
./middleware/u8glib/fntsrc/u8g_font_fub14r.o \
./middleware/u8glib/fntsrc/u8g_font_fub17.o \
./middleware/u8glib/fntsrc/u8g_font_fub17n.o \
./middleware/u8glib/fntsrc/u8g_font_fub17r.o \
./middleware/u8glib/fntsrc/u8g_font_fub20.o \
./middleware/u8glib/fntsrc/u8g_font_fub20n.o \
./middleware/u8glib/fntsrc/u8g_font_fub20r.o \
./middleware/u8glib/fntsrc/u8g_font_fub25.o \
./middleware/u8glib/fntsrc/u8g_font_fub25n.o \
./middleware/u8glib/fntsrc/u8g_font_fub25r.o \
./middleware/u8glib/fntsrc/u8g_font_fub30.o \
./middleware/u8glib/fntsrc/u8g_font_fub30n.o \
./middleware/u8glib/fntsrc/u8g_font_fub30r.o \
./middleware/u8glib/fntsrc/u8g_font_fub35n.o \
./middleware/u8glib/fntsrc/u8g_font_fub42n.o \
./middleware/u8glib/fntsrc/u8g_font_fub49n.o \
./middleware/u8glib/fntsrc/u8g_font_fur11.o \
./middleware/u8glib/fntsrc/u8g_font_fur11n.o \
./middleware/u8glib/fntsrc/u8g_font_fur11r.o \
./middleware/u8glib/fntsrc/u8g_font_fur14.o \
./middleware/u8glib/fntsrc/u8g_font_fur14n.o \
./middleware/u8glib/fntsrc/u8g_font_fur14r.o \
./middleware/u8glib/fntsrc/u8g_font_fur17.o \
./middleware/u8glib/fntsrc/u8g_font_fur17n.o \
./middleware/u8glib/fntsrc/u8g_font_fur17r.o \
./middleware/u8glib/fntsrc/u8g_font_fur20.o \
./middleware/u8glib/fntsrc/u8g_font_fur20n.o \
./middleware/u8glib/fntsrc/u8g_font_fur20r.o \
./middleware/u8glib/fntsrc/u8g_font_fur25.o \
./middleware/u8glib/fntsrc/u8g_font_fur25n.o \
./middleware/u8glib/fntsrc/u8g_font_fur25r.o \
./middleware/u8glib/fntsrc/u8g_font_fur30.o \
./middleware/u8glib/fntsrc/u8g_font_fur30n.o \
./middleware/u8glib/fntsrc/u8g_font_fur30r.o \
./middleware/u8glib/fntsrc/u8g_font_fur35n.o \
./middleware/u8glib/fntsrc/u8g_font_fur42n.o \
./middleware/u8glib/fntsrc/u8g_font_fur49n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb11.o \
./middleware/u8glib/fntsrc/u8g_font_gdb11n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb11r.o \
./middleware/u8glib/fntsrc/u8g_font_gdb12.o \
./middleware/u8glib/fntsrc/u8g_font_gdb12n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb12r.o \
./middleware/u8glib/fntsrc/u8g_font_gdb14.o \
./middleware/u8glib/fntsrc/u8g_font_gdb14n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb14r.o \
./middleware/u8glib/fntsrc/u8g_font_gdb17.o \
./middleware/u8glib/fntsrc/u8g_font_gdb17n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb17r.o \
./middleware/u8glib/fntsrc/u8g_font_gdb20.o \
./middleware/u8glib/fntsrc/u8g_font_gdb20n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb20r.o \
./middleware/u8glib/fntsrc/u8g_font_gdb25.o \
./middleware/u8glib/fntsrc/u8g_font_gdb25n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb25r.o \
./middleware/u8glib/fntsrc/u8g_font_gdb30.o \
./middleware/u8glib/fntsrc/u8g_font_gdb30n.o \
./middleware/u8glib/fntsrc/u8g_font_gdb30r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr10.o \
./middleware/u8glib/fntsrc/u8g_font_gdr10n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr10r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr11.o \
./middleware/u8glib/fntsrc/u8g_font_gdr11n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr11r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr12.o \
./middleware/u8glib/fntsrc/u8g_font_gdr12n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr12r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr14.o \
./middleware/u8glib/fntsrc/u8g_font_gdr14n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr14r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr17.o \
./middleware/u8glib/fntsrc/u8g_font_gdr17n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr17r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr20.o \
./middleware/u8glib/fntsrc/u8g_font_gdr20n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr20r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr25.o \
./middleware/u8glib/fntsrc/u8g_font_gdr25n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr25r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr30.o \
./middleware/u8glib/fntsrc/u8g_font_gdr30n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr30r.o \
./middleware/u8glib/fntsrc/u8g_font_gdr9.o \
./middleware/u8glib/fntsrc/u8g_font_gdr9n.o \
./middleware/u8glib/fntsrc/u8g_font_gdr9r.o \
./middleware/u8glib/fntsrc/u8g_font_helvb08.o \
./middleware/u8glib/fntsrc/u8g_font_helvb08n.o \
./middleware/u8glib/fntsrc/u8g_font_helvb08r.o \
./middleware/u8glib/fntsrc/u8g_font_helvb10.o \
./middleware/u8glib/fntsrc/u8g_font_helvb10n.o \
./middleware/u8glib/fntsrc/u8g_font_helvb10r.o \
./middleware/u8glib/fntsrc/u8g_font_helvb12.o \
./middleware/u8glib/fntsrc/u8g_font_helvb12n.o \
./middleware/u8glib/fntsrc/u8g_font_helvb12r.o \
./middleware/u8glib/fntsrc/u8g_font_helvb14.o \
./middleware/u8glib/fntsrc/u8g_font_helvb14n.o \
./middleware/u8glib/fntsrc/u8g_font_helvb14r.o \
./middleware/u8glib/fntsrc/u8g_font_helvb18.o \
./middleware/u8glib/fntsrc/u8g_font_helvb18n.o \
./middleware/u8glib/fntsrc/u8g_font_helvb18r.o \
./middleware/u8glib/fntsrc/u8g_font_helvb24.o \
./middleware/u8glib/fntsrc/u8g_font_helvb24n.o \
./middleware/u8glib/fntsrc/u8g_font_helvb24r.o \
./middleware/u8glib/fntsrc/u8g_font_helvr08.o \
./middleware/u8glib/fntsrc/u8g_font_helvr08r.o \
./middleware/u8glib/fntsrc/u8g_font_helvr10.o \
./middleware/u8glib/fntsrc/u8g_font_helvr10r.o \
./middleware/u8glib/fntsrc/u8g_font_helvr12.o \
./middleware/u8glib/fntsrc/u8g_font_helvr12r.o \
./middleware/u8glib/fntsrc/u8g_font_helvr14.o \
./middleware/u8glib/fntsrc/u8g_font_helvr14r.o \
./middleware/u8glib/fntsrc/u8g_font_helvr18.o \
./middleware/u8glib/fntsrc/u8g_font_helvr18r.o \
./middleware/u8glib/fntsrc/u8g_font_helvr24.o \
./middleware/u8glib/fntsrc/u8g_font_helvr24n.o \
./middleware/u8glib/fntsrc/u8g_font_helvr24r.o \
./middleware/u8glib/fntsrc/u8g_font_lucasfont_alternate.o \
./middleware/u8glib/fntsrc/u8g_font_lucasfont_alternaten.o \
./middleware/u8glib/fntsrc/u8g_font_lucasfont_alternater.o \
./middleware/u8glib/fntsrc/u8g_font_m2icon_5.o \
./middleware/u8glib/fntsrc/u8g_font_m2icon_7.o \
./middleware/u8glib/fntsrc/u8g_font_m2icon_9.o \
./middleware/u8glib/fntsrc/u8g_font_micro.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb08.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb08r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb10.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb10r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb12.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb12r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb14.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb14r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb18.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb18r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb24.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb24n.o \
./middleware/u8glib/fntsrc/u8g_font_ncenb24r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr08.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr08r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr10.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr10r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr12.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr12r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr14.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr14r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr18.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr18r.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr24.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr24n.o \
./middleware/u8glib/fntsrc/u8g_font_ncenr24r.o \
./middleware/u8glib/fntsrc/u8g_font_orgv01.o \
./middleware/u8glib/fntsrc/u8g_font_orgv01n.o \
./middleware/u8glib/fntsrc/u8g_font_orgv01r.o \
./middleware/u8glib/fntsrc/u8g_font_osb18.o \
./middleware/u8glib/fntsrc/u8g_font_osb18n.o \
./middleware/u8glib/fntsrc/u8g_font_osb18r.o \
./middleware/u8glib/fntsrc/u8g_font_osb21.o \
./middleware/u8glib/fntsrc/u8g_font_osb21n.o \
./middleware/u8glib/fntsrc/u8g_font_osb21r.o \
./middleware/u8glib/fntsrc/u8g_font_osb26.o \
./middleware/u8glib/fntsrc/u8g_font_osb26n.o \
./middleware/u8glib/fntsrc/u8g_font_osb26r.o \
./middleware/u8glib/fntsrc/u8g_font_osb29.o \
./middleware/u8glib/fntsrc/u8g_font_osb29n.o \
./middleware/u8glib/fntsrc/u8g_font_osb29r.o \
./middleware/u8glib/fntsrc/u8g_font_osb35.o \
./middleware/u8glib/fntsrc/u8g_font_osb35n.o \
./middleware/u8glib/fntsrc/u8g_font_osb35r.o \
./middleware/u8glib/fntsrc/u8g_font_osr18.o \
./middleware/u8glib/fntsrc/u8g_font_osr18n.o \
./middleware/u8glib/fntsrc/u8g_font_osr18r.o \
./middleware/u8glib/fntsrc/u8g_font_osr21.o \
./middleware/u8glib/fntsrc/u8g_font_osr21n.o \
./middleware/u8glib/fntsrc/u8g_font_osr21r.o \
./middleware/u8glib/fntsrc/u8g_font_osr26.o \
./middleware/u8glib/fntsrc/u8g_font_osr26n.o \
./middleware/u8glib/fntsrc/u8g_font_osr26r.o \
./middleware/u8glib/fntsrc/u8g_font_osr29.o \
./middleware/u8glib/fntsrc/u8g_font_osr29n.o \
./middleware/u8glib/fntsrc/u8g_font_osr29r.o \
./middleware/u8glib/fntsrc/u8g_font_osr35.o \
./middleware/u8glib/fntsrc/u8g_font_osr35n.o \
./middleware/u8glib/fntsrc/u8g_font_osr35r.o \
./middleware/u8glib/fntsrc/u8g_font_p01type.o \
./middleware/u8glib/fntsrc/u8g_font_p01typen.o \
./middleware/u8glib/fntsrc/u8g_font_p01typer.o \
./middleware/u8glib/fntsrc/u8g_font_pixelle_micro.o \
./middleware/u8glib/fntsrc/u8g_font_pixelle_micron.o \
./middleware/u8glib/fntsrc/u8g_font_pixelle_micror.o \
./middleware/u8glib/fntsrc/u8g_font_profont10.o \
./middleware/u8glib/fntsrc/u8g_font_profont10r.o \
./middleware/u8glib/fntsrc/u8g_font_profont11.o \
./middleware/u8glib/fntsrc/u8g_font_profont11r.o \
./middleware/u8glib/fntsrc/u8g_font_profont12.o \
./middleware/u8glib/fntsrc/u8g_font_profont12r.o \
./middleware/u8glib/fntsrc/u8g_font_profont15.o \
./middleware/u8glib/fntsrc/u8g_font_profont15r.o \
./middleware/u8glib/fntsrc/u8g_font_profont17.o \
./middleware/u8glib/fntsrc/u8g_font_profont17r.o \
./middleware/u8glib/fntsrc/u8g_font_profont22.o \
./middleware/u8glib/fntsrc/u8g_font_profont22r.o \
./middleware/u8glib/fntsrc/u8g_font_profont29.o \
./middleware/u8glib/fntsrc/u8g_font_profont29r.o \
./middleware/u8glib/fntsrc/u8g_font_robot_de_niro.o \
./middleware/u8glib/fntsrc/u8g_font_robot_de_niron.o \
./middleware/u8glib/fntsrc/u8g_font_robot_de_niror.o \
./middleware/u8glib/fntsrc/u8g_font_symb08.o \
./middleware/u8glib/fntsrc/u8g_font_symb08r.o \
./middleware/u8glib/fntsrc/u8g_font_symb10.o \
./middleware/u8glib/fntsrc/u8g_font_symb10r.o \
./middleware/u8glib/fntsrc/u8g_font_symb12.o \
./middleware/u8glib/fntsrc/u8g_font_symb12r.o \
./middleware/u8glib/fntsrc/u8g_font_symb14.o \
./middleware/u8glib/fntsrc/u8g_font_symb14r.o \
./middleware/u8glib/fntsrc/u8g_font_symb18.o \
./middleware/u8glib/fntsrc/u8g_font_symb18r.o \
./middleware/u8glib/fntsrc/u8g_font_symb24.o \
./middleware/u8glib/fntsrc/u8g_font_symb24r.o \
./middleware/u8glib/fntsrc/u8g_font_timb08.o \
./middleware/u8glib/fntsrc/u8g_font_timb08r.o \
./middleware/u8glib/fntsrc/u8g_font_timb10.o \
./middleware/u8glib/fntsrc/u8g_font_timb10r.o \
./middleware/u8glib/fntsrc/u8g_font_timb12.o \
./middleware/u8glib/fntsrc/u8g_font_timb12r.o \
./middleware/u8glib/fntsrc/u8g_font_timb14.o \
./middleware/u8glib/fntsrc/u8g_font_timb14r.o \
./middleware/u8glib/fntsrc/u8g_font_timb18.o \
./middleware/u8glib/fntsrc/u8g_font_timb18r.o \
./middleware/u8glib/fntsrc/u8g_font_timb24.o \
./middleware/u8glib/fntsrc/u8g_font_timb24n.o \
./middleware/u8glib/fntsrc/u8g_font_timb24r.o \
./middleware/u8glib/fntsrc/u8g_font_timr08.o \
./middleware/u8glib/fntsrc/u8g_font_timr08r.o \
./middleware/u8glib/fntsrc/u8g_font_timr10.o \
./middleware/u8glib/fntsrc/u8g_font_timr10r.o \
./middleware/u8glib/fntsrc/u8g_font_timr12.o \
./middleware/u8glib/fntsrc/u8g_font_timr12r.o \
./middleware/u8glib/fntsrc/u8g_font_timr14.o \
./middleware/u8glib/fntsrc/u8g_font_timr14r.o \
./middleware/u8glib/fntsrc/u8g_font_timr18.o \
./middleware/u8glib/fntsrc/u8g_font_timr18r.o \
./middleware/u8glib/fntsrc/u8g_font_timr24.o \
./middleware/u8glib/fntsrc/u8g_font_timr24n.o \
./middleware/u8glib/fntsrc/u8g_font_timr24r.o \
./middleware/u8glib/fntsrc/u8g_font_tpss.o \
./middleware/u8glib/fntsrc/u8g_font_tpssb.o \
./middleware/u8glib/fntsrc/u8g_font_tpssbn.o \
./middleware/u8glib/fntsrc/u8g_font_tpssbr.o \
./middleware/u8glib/fntsrc/u8g_font_tpssn.o \
./middleware/u8glib/fntsrc/u8g_font_tpssr.o \
./middleware/u8glib/fntsrc/u8g_font_trixel_square.o \
./middleware/u8glib/fntsrc/u8g_font_trixel_squaren.o \
./middleware/u8glib/fntsrc/u8g_font_trixel_squarer.o \
./middleware/u8glib/fntsrc/u8g_font_u8glib_4.o \
./middleware/u8glib/fntsrc/u8g_font_u8glib_4r.o \
./middleware/u8glib/fntsrc/u8g_font_unifont.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_0_8.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_12_13.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_18_19.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_2_3.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_4_5.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_67_75.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_72_73.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_75r.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_76.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_77.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_78_79.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_86.o \
./middleware/u8glib/fntsrc/u8g_font_unifont_8_9.o \
./middleware/u8glib/fntsrc/u8g_font_unifontr.o 

C_DEPS += \
./middleware/u8glib/fntsrc/u8g_font_04b_03.d \
./middleware/u8glib/fntsrc/u8g_font_04b_03b.d \
./middleware/u8glib/fntsrc/u8g_font_04b_03bn.d \
./middleware/u8glib/fntsrc/u8g_font_04b_03br.d \
./middleware/u8glib/fntsrc/u8g_font_04b_03n.d \
./middleware/u8glib/fntsrc/u8g_font_04b_03r.d \
./middleware/u8glib/fntsrc/u8g_font_04b_24.d \
./middleware/u8glib/fntsrc/u8g_font_04b_24n.d \
./middleware/u8glib/fntsrc/u8g_font_04b_24r.d \
./middleware/u8glib/fntsrc/u8g_font_10x20.d \
./middleware/u8glib/fntsrc/u8g_font_10x20_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_10x20_75r.d \
./middleware/u8glib/fntsrc/u8g_font_10x20_78_79.d \
./middleware/u8glib/fntsrc/u8g_font_10x20r.d \
./middleware/u8glib/fntsrc/u8g_font_4x6.d \
./middleware/u8glib/fntsrc/u8g_font_4x6r.d \
./middleware/u8glib/fntsrc/u8g_font_5x7.d \
./middleware/u8glib/fntsrc/u8g_font_5x7r.d \
./middleware/u8glib/fntsrc/u8g_font_5x8.d \
./middleware/u8glib/fntsrc/u8g_font_5x8r.d \
./middleware/u8glib/fntsrc/u8g_font_6x10.d \
./middleware/u8glib/fntsrc/u8g_font_6x10r.d \
./middleware/u8glib/fntsrc/u8g_font_6x12.d \
./middleware/u8glib/fntsrc/u8g_font_6x12_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_6x12_75r.d \
./middleware/u8glib/fntsrc/u8g_font_6x12_78_79.d \
./middleware/u8glib/fntsrc/u8g_font_6x12r.d \
./middleware/u8glib/fntsrc/u8g_font_6x13.d \
./middleware/u8glib/fntsrc/u8g_font_6x13B.d \
./middleware/u8glib/fntsrc/u8g_font_6x13Br.d \
./middleware/u8glib/fntsrc/u8g_font_6x13O.d \
./middleware/u8glib/fntsrc/u8g_font_6x13Or.d \
./middleware/u8glib/fntsrc/u8g_font_6x13_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_6x13_75r.d \
./middleware/u8glib/fntsrc/u8g_font_6x13_78_79.d \
./middleware/u8glib/fntsrc/u8g_font_6x13r.d \
./middleware/u8glib/fntsrc/u8g_font_7x13.d \
./middleware/u8glib/fntsrc/u8g_font_7x13B.d \
./middleware/u8glib/fntsrc/u8g_font_7x13Br.d \
./middleware/u8glib/fntsrc/u8g_font_7x13O.d \
./middleware/u8glib/fntsrc/u8g_font_7x13Or.d \
./middleware/u8glib/fntsrc/u8g_font_7x13_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_7x13_75r.d \
./middleware/u8glib/fntsrc/u8g_font_7x13r.d \
./middleware/u8glib/fntsrc/u8g_font_7x14.d \
./middleware/u8glib/fntsrc/u8g_font_7x14B.d \
./middleware/u8glib/fntsrc/u8g_font_7x14Br.d \
./middleware/u8glib/fntsrc/u8g_font_7x14r.d \
./middleware/u8glib/fntsrc/u8g_font_8x13.d \
./middleware/u8glib/fntsrc/u8g_font_8x13B.d \
./middleware/u8glib/fntsrc/u8g_font_8x13Br.d \
./middleware/u8glib/fntsrc/u8g_font_8x13O.d \
./middleware/u8glib/fntsrc/u8g_font_8x13Or.d \
./middleware/u8glib/fntsrc/u8g_font_8x13_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_8x13_75r.d \
./middleware/u8glib/fntsrc/u8g_font_8x13r.d \
./middleware/u8glib/fntsrc/u8g_font_9x15.d \
./middleware/u8glib/fntsrc/u8g_font_9x15B.d \
./middleware/u8glib/fntsrc/u8g_font_9x15Br.d \
./middleware/u8glib/fntsrc/u8g_font_9x15_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_9x15_75r.d \
./middleware/u8glib/fntsrc/u8g_font_9x15_78_79.d \
./middleware/u8glib/fntsrc/u8g_font_9x15r.d \
./middleware/u8glib/fntsrc/u8g_font_9x18.d \
./middleware/u8glib/fntsrc/u8g_font_9x18B.d \
./middleware/u8glib/fntsrc/u8g_font_9x18Br.d \
./middleware/u8glib/fntsrc/u8g_font_9x18_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_9x18_75r.d \
./middleware/u8glib/fntsrc/u8g_font_9x18_78_79.d \
./middleware/u8glib/fntsrc/u8g_font_9x18r.d \
./middleware/u8glib/fntsrc/u8g_font_baby.d \
./middleware/u8glib/fntsrc/u8g_font_babyn.d \
./middleware/u8glib/fntsrc/u8g_font_babyr.d \
./middleware/u8glib/fntsrc/u8g_font_blipfest_07.d \
./middleware/u8glib/fntsrc/u8g_font_blipfest_07n.d \
./middleware/u8glib/fntsrc/u8g_font_blipfest_07r.d \
./middleware/u8glib/fntsrc/u8g_font_chikita.d \
./middleware/u8glib/fntsrc/u8g_font_chikitan.d \
./middleware/u8glib/fntsrc/u8g_font_chikitar.d \
./middleware/u8glib/fntsrc/u8g_font_courb08.d \
./middleware/u8glib/fntsrc/u8g_font_courb08r.d \
./middleware/u8glib/fntsrc/u8g_font_courb10.d \
./middleware/u8glib/fntsrc/u8g_font_courb10r.d \
./middleware/u8glib/fntsrc/u8g_font_courb12.d \
./middleware/u8glib/fntsrc/u8g_font_courb12r.d \
./middleware/u8glib/fntsrc/u8g_font_courb14.d \
./middleware/u8glib/fntsrc/u8g_font_courb14r.d \
./middleware/u8glib/fntsrc/u8g_font_courb18.d \
./middleware/u8glib/fntsrc/u8g_font_courb18r.d \
./middleware/u8glib/fntsrc/u8g_font_courb24.d \
./middleware/u8glib/fntsrc/u8g_font_courb24r.d \
./middleware/u8glib/fntsrc/u8g_font_courb4n.d \
./middleware/u8glib/fntsrc/u8g_font_courr08.d \
./middleware/u8glib/fntsrc/u8g_font_courr08r.d \
./middleware/u8glib/fntsrc/u8g_font_courr10.d \
./middleware/u8glib/fntsrc/u8g_font_courr10r.d \
./middleware/u8glib/fntsrc/u8g_font_courr12.d \
./middleware/u8glib/fntsrc/u8g_font_courr12r.d \
./middleware/u8glib/fntsrc/u8g_font_courr14.d \
./middleware/u8glib/fntsrc/u8g_font_courr14r.d \
./middleware/u8glib/fntsrc/u8g_font_courr18.d \
./middleware/u8glib/fntsrc/u8g_font_courr18r.d \
./middleware/u8glib/fntsrc/u8g_font_courr24.d \
./middleware/u8glib/fntsrc/u8g_font_courr24n.d \
./middleware/u8glib/fntsrc/u8g_font_courr24r.d \
./middleware/u8glib/fntsrc/u8g_font_cu12.d \
./middleware/u8glib/fntsrc/u8g_font_cu12_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_cu12_75r.d \
./middleware/u8glib/fntsrc/u8g_font_cursor.d \
./middleware/u8glib/fntsrc/u8g_font_cursorr.d \
./middleware/u8glib/fntsrc/u8g_font_fixed_v0.d \
./middleware/u8glib/fntsrc/u8g_font_fixed_v0n.d \
./middleware/u8glib/fntsrc/u8g_font_fixed_v0r.d \
./middleware/u8glib/fntsrc/u8g_font_freedoomr10r.d \
./middleware/u8glib/fntsrc/u8g_font_freedoomr25n.d \
./middleware/u8glib/fntsrc/u8g_font_fub11.d \
./middleware/u8glib/fntsrc/u8g_font_fub11n.d \
./middleware/u8glib/fntsrc/u8g_font_fub11r.d \
./middleware/u8glib/fntsrc/u8g_font_fub14.d \
./middleware/u8glib/fntsrc/u8g_font_fub14n.d \
./middleware/u8glib/fntsrc/u8g_font_fub14r.d \
./middleware/u8glib/fntsrc/u8g_font_fub17.d \
./middleware/u8glib/fntsrc/u8g_font_fub17n.d \
./middleware/u8glib/fntsrc/u8g_font_fub17r.d \
./middleware/u8glib/fntsrc/u8g_font_fub20.d \
./middleware/u8glib/fntsrc/u8g_font_fub20n.d \
./middleware/u8glib/fntsrc/u8g_font_fub20r.d \
./middleware/u8glib/fntsrc/u8g_font_fub25.d \
./middleware/u8glib/fntsrc/u8g_font_fub25n.d \
./middleware/u8glib/fntsrc/u8g_font_fub25r.d \
./middleware/u8glib/fntsrc/u8g_font_fub30.d \
./middleware/u8glib/fntsrc/u8g_font_fub30n.d \
./middleware/u8glib/fntsrc/u8g_font_fub30r.d \
./middleware/u8glib/fntsrc/u8g_font_fub35n.d \
./middleware/u8glib/fntsrc/u8g_font_fub42n.d \
./middleware/u8glib/fntsrc/u8g_font_fub49n.d \
./middleware/u8glib/fntsrc/u8g_font_fur11.d \
./middleware/u8glib/fntsrc/u8g_font_fur11n.d \
./middleware/u8glib/fntsrc/u8g_font_fur11r.d \
./middleware/u8glib/fntsrc/u8g_font_fur14.d \
./middleware/u8glib/fntsrc/u8g_font_fur14n.d \
./middleware/u8glib/fntsrc/u8g_font_fur14r.d \
./middleware/u8glib/fntsrc/u8g_font_fur17.d \
./middleware/u8glib/fntsrc/u8g_font_fur17n.d \
./middleware/u8glib/fntsrc/u8g_font_fur17r.d \
./middleware/u8glib/fntsrc/u8g_font_fur20.d \
./middleware/u8glib/fntsrc/u8g_font_fur20n.d \
./middleware/u8glib/fntsrc/u8g_font_fur20r.d \
./middleware/u8glib/fntsrc/u8g_font_fur25.d \
./middleware/u8glib/fntsrc/u8g_font_fur25n.d \
./middleware/u8glib/fntsrc/u8g_font_fur25r.d \
./middleware/u8glib/fntsrc/u8g_font_fur30.d \
./middleware/u8glib/fntsrc/u8g_font_fur30n.d \
./middleware/u8glib/fntsrc/u8g_font_fur30r.d \
./middleware/u8glib/fntsrc/u8g_font_fur35n.d \
./middleware/u8glib/fntsrc/u8g_font_fur42n.d \
./middleware/u8glib/fntsrc/u8g_font_fur49n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb11.d \
./middleware/u8glib/fntsrc/u8g_font_gdb11n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb11r.d \
./middleware/u8glib/fntsrc/u8g_font_gdb12.d \
./middleware/u8glib/fntsrc/u8g_font_gdb12n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb12r.d \
./middleware/u8glib/fntsrc/u8g_font_gdb14.d \
./middleware/u8glib/fntsrc/u8g_font_gdb14n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb14r.d \
./middleware/u8glib/fntsrc/u8g_font_gdb17.d \
./middleware/u8glib/fntsrc/u8g_font_gdb17n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb17r.d \
./middleware/u8glib/fntsrc/u8g_font_gdb20.d \
./middleware/u8glib/fntsrc/u8g_font_gdb20n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb20r.d \
./middleware/u8glib/fntsrc/u8g_font_gdb25.d \
./middleware/u8glib/fntsrc/u8g_font_gdb25n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb25r.d \
./middleware/u8glib/fntsrc/u8g_font_gdb30.d \
./middleware/u8glib/fntsrc/u8g_font_gdb30n.d \
./middleware/u8glib/fntsrc/u8g_font_gdb30r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr10.d \
./middleware/u8glib/fntsrc/u8g_font_gdr10n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr10r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr11.d \
./middleware/u8glib/fntsrc/u8g_font_gdr11n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr11r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr12.d \
./middleware/u8glib/fntsrc/u8g_font_gdr12n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr12r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr14.d \
./middleware/u8glib/fntsrc/u8g_font_gdr14n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr14r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr17.d \
./middleware/u8glib/fntsrc/u8g_font_gdr17n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr17r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr20.d \
./middleware/u8glib/fntsrc/u8g_font_gdr20n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr20r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr25.d \
./middleware/u8glib/fntsrc/u8g_font_gdr25n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr25r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr30.d \
./middleware/u8glib/fntsrc/u8g_font_gdr30n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr30r.d \
./middleware/u8glib/fntsrc/u8g_font_gdr9.d \
./middleware/u8glib/fntsrc/u8g_font_gdr9n.d \
./middleware/u8glib/fntsrc/u8g_font_gdr9r.d \
./middleware/u8glib/fntsrc/u8g_font_helvb08.d \
./middleware/u8glib/fntsrc/u8g_font_helvb08n.d \
./middleware/u8glib/fntsrc/u8g_font_helvb08r.d \
./middleware/u8glib/fntsrc/u8g_font_helvb10.d \
./middleware/u8glib/fntsrc/u8g_font_helvb10n.d \
./middleware/u8glib/fntsrc/u8g_font_helvb10r.d \
./middleware/u8glib/fntsrc/u8g_font_helvb12.d \
./middleware/u8glib/fntsrc/u8g_font_helvb12n.d \
./middleware/u8glib/fntsrc/u8g_font_helvb12r.d \
./middleware/u8glib/fntsrc/u8g_font_helvb14.d \
./middleware/u8glib/fntsrc/u8g_font_helvb14n.d \
./middleware/u8glib/fntsrc/u8g_font_helvb14r.d \
./middleware/u8glib/fntsrc/u8g_font_helvb18.d \
./middleware/u8glib/fntsrc/u8g_font_helvb18n.d \
./middleware/u8glib/fntsrc/u8g_font_helvb18r.d \
./middleware/u8glib/fntsrc/u8g_font_helvb24.d \
./middleware/u8glib/fntsrc/u8g_font_helvb24n.d \
./middleware/u8glib/fntsrc/u8g_font_helvb24r.d \
./middleware/u8glib/fntsrc/u8g_font_helvr08.d \
./middleware/u8glib/fntsrc/u8g_font_helvr08r.d \
./middleware/u8glib/fntsrc/u8g_font_helvr10.d \
./middleware/u8glib/fntsrc/u8g_font_helvr10r.d \
./middleware/u8glib/fntsrc/u8g_font_helvr12.d \
./middleware/u8glib/fntsrc/u8g_font_helvr12r.d \
./middleware/u8glib/fntsrc/u8g_font_helvr14.d \
./middleware/u8glib/fntsrc/u8g_font_helvr14r.d \
./middleware/u8glib/fntsrc/u8g_font_helvr18.d \
./middleware/u8glib/fntsrc/u8g_font_helvr18r.d \
./middleware/u8glib/fntsrc/u8g_font_helvr24.d \
./middleware/u8glib/fntsrc/u8g_font_helvr24n.d \
./middleware/u8glib/fntsrc/u8g_font_helvr24r.d \
./middleware/u8glib/fntsrc/u8g_font_lucasfont_alternate.d \
./middleware/u8glib/fntsrc/u8g_font_lucasfont_alternaten.d \
./middleware/u8glib/fntsrc/u8g_font_lucasfont_alternater.d \
./middleware/u8glib/fntsrc/u8g_font_m2icon_5.d \
./middleware/u8glib/fntsrc/u8g_font_m2icon_7.d \
./middleware/u8glib/fntsrc/u8g_font_m2icon_9.d \
./middleware/u8glib/fntsrc/u8g_font_micro.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb08.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb08r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb10.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb10r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb12.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb12r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb14.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb14r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb18.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb18r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb24.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb24n.d \
./middleware/u8glib/fntsrc/u8g_font_ncenb24r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr08.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr08r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr10.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr10r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr12.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr12r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr14.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr14r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr18.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr18r.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr24.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr24n.d \
./middleware/u8glib/fntsrc/u8g_font_ncenr24r.d \
./middleware/u8glib/fntsrc/u8g_font_orgv01.d \
./middleware/u8glib/fntsrc/u8g_font_orgv01n.d \
./middleware/u8glib/fntsrc/u8g_font_orgv01r.d \
./middleware/u8glib/fntsrc/u8g_font_osb18.d \
./middleware/u8glib/fntsrc/u8g_font_osb18n.d \
./middleware/u8glib/fntsrc/u8g_font_osb18r.d \
./middleware/u8glib/fntsrc/u8g_font_osb21.d \
./middleware/u8glib/fntsrc/u8g_font_osb21n.d \
./middleware/u8glib/fntsrc/u8g_font_osb21r.d \
./middleware/u8glib/fntsrc/u8g_font_osb26.d \
./middleware/u8glib/fntsrc/u8g_font_osb26n.d \
./middleware/u8glib/fntsrc/u8g_font_osb26r.d \
./middleware/u8glib/fntsrc/u8g_font_osb29.d \
./middleware/u8glib/fntsrc/u8g_font_osb29n.d \
./middleware/u8glib/fntsrc/u8g_font_osb29r.d \
./middleware/u8glib/fntsrc/u8g_font_osb35.d \
./middleware/u8glib/fntsrc/u8g_font_osb35n.d \
./middleware/u8glib/fntsrc/u8g_font_osb35r.d \
./middleware/u8glib/fntsrc/u8g_font_osr18.d \
./middleware/u8glib/fntsrc/u8g_font_osr18n.d \
./middleware/u8glib/fntsrc/u8g_font_osr18r.d \
./middleware/u8glib/fntsrc/u8g_font_osr21.d \
./middleware/u8glib/fntsrc/u8g_font_osr21n.d \
./middleware/u8glib/fntsrc/u8g_font_osr21r.d \
./middleware/u8glib/fntsrc/u8g_font_osr26.d \
./middleware/u8glib/fntsrc/u8g_font_osr26n.d \
./middleware/u8glib/fntsrc/u8g_font_osr26r.d \
./middleware/u8glib/fntsrc/u8g_font_osr29.d \
./middleware/u8glib/fntsrc/u8g_font_osr29n.d \
./middleware/u8glib/fntsrc/u8g_font_osr29r.d \
./middleware/u8glib/fntsrc/u8g_font_osr35.d \
./middleware/u8glib/fntsrc/u8g_font_osr35n.d \
./middleware/u8glib/fntsrc/u8g_font_osr35r.d \
./middleware/u8glib/fntsrc/u8g_font_p01type.d \
./middleware/u8glib/fntsrc/u8g_font_p01typen.d \
./middleware/u8glib/fntsrc/u8g_font_p01typer.d \
./middleware/u8glib/fntsrc/u8g_font_pixelle_micro.d \
./middleware/u8glib/fntsrc/u8g_font_pixelle_micron.d \
./middleware/u8glib/fntsrc/u8g_font_pixelle_micror.d \
./middleware/u8glib/fntsrc/u8g_font_profont10.d \
./middleware/u8glib/fntsrc/u8g_font_profont10r.d \
./middleware/u8glib/fntsrc/u8g_font_profont11.d \
./middleware/u8glib/fntsrc/u8g_font_profont11r.d \
./middleware/u8glib/fntsrc/u8g_font_profont12.d \
./middleware/u8glib/fntsrc/u8g_font_profont12r.d \
./middleware/u8glib/fntsrc/u8g_font_profont15.d \
./middleware/u8glib/fntsrc/u8g_font_profont15r.d \
./middleware/u8glib/fntsrc/u8g_font_profont17.d \
./middleware/u8glib/fntsrc/u8g_font_profont17r.d \
./middleware/u8glib/fntsrc/u8g_font_profont22.d \
./middleware/u8glib/fntsrc/u8g_font_profont22r.d \
./middleware/u8glib/fntsrc/u8g_font_profont29.d \
./middleware/u8glib/fntsrc/u8g_font_profont29r.d \
./middleware/u8glib/fntsrc/u8g_font_robot_de_niro.d \
./middleware/u8glib/fntsrc/u8g_font_robot_de_niron.d \
./middleware/u8glib/fntsrc/u8g_font_robot_de_niror.d \
./middleware/u8glib/fntsrc/u8g_font_symb08.d \
./middleware/u8glib/fntsrc/u8g_font_symb08r.d \
./middleware/u8glib/fntsrc/u8g_font_symb10.d \
./middleware/u8glib/fntsrc/u8g_font_symb10r.d \
./middleware/u8glib/fntsrc/u8g_font_symb12.d \
./middleware/u8glib/fntsrc/u8g_font_symb12r.d \
./middleware/u8glib/fntsrc/u8g_font_symb14.d \
./middleware/u8glib/fntsrc/u8g_font_symb14r.d \
./middleware/u8glib/fntsrc/u8g_font_symb18.d \
./middleware/u8glib/fntsrc/u8g_font_symb18r.d \
./middleware/u8glib/fntsrc/u8g_font_symb24.d \
./middleware/u8glib/fntsrc/u8g_font_symb24r.d \
./middleware/u8glib/fntsrc/u8g_font_timb08.d \
./middleware/u8glib/fntsrc/u8g_font_timb08r.d \
./middleware/u8glib/fntsrc/u8g_font_timb10.d \
./middleware/u8glib/fntsrc/u8g_font_timb10r.d \
./middleware/u8glib/fntsrc/u8g_font_timb12.d \
./middleware/u8glib/fntsrc/u8g_font_timb12r.d \
./middleware/u8glib/fntsrc/u8g_font_timb14.d \
./middleware/u8glib/fntsrc/u8g_font_timb14r.d \
./middleware/u8glib/fntsrc/u8g_font_timb18.d \
./middleware/u8glib/fntsrc/u8g_font_timb18r.d \
./middleware/u8glib/fntsrc/u8g_font_timb24.d \
./middleware/u8glib/fntsrc/u8g_font_timb24n.d \
./middleware/u8glib/fntsrc/u8g_font_timb24r.d \
./middleware/u8glib/fntsrc/u8g_font_timr08.d \
./middleware/u8glib/fntsrc/u8g_font_timr08r.d \
./middleware/u8glib/fntsrc/u8g_font_timr10.d \
./middleware/u8glib/fntsrc/u8g_font_timr10r.d \
./middleware/u8glib/fntsrc/u8g_font_timr12.d \
./middleware/u8glib/fntsrc/u8g_font_timr12r.d \
./middleware/u8glib/fntsrc/u8g_font_timr14.d \
./middleware/u8glib/fntsrc/u8g_font_timr14r.d \
./middleware/u8glib/fntsrc/u8g_font_timr18.d \
./middleware/u8glib/fntsrc/u8g_font_timr18r.d \
./middleware/u8glib/fntsrc/u8g_font_timr24.d \
./middleware/u8glib/fntsrc/u8g_font_timr24n.d \
./middleware/u8glib/fntsrc/u8g_font_timr24r.d \
./middleware/u8glib/fntsrc/u8g_font_tpss.d \
./middleware/u8glib/fntsrc/u8g_font_tpssb.d \
./middleware/u8glib/fntsrc/u8g_font_tpssbn.d \
./middleware/u8glib/fntsrc/u8g_font_tpssbr.d \
./middleware/u8glib/fntsrc/u8g_font_tpssn.d \
./middleware/u8glib/fntsrc/u8g_font_tpssr.d \
./middleware/u8glib/fntsrc/u8g_font_trixel_square.d \
./middleware/u8glib/fntsrc/u8g_font_trixel_squaren.d \
./middleware/u8glib/fntsrc/u8g_font_trixel_squarer.d \
./middleware/u8glib/fntsrc/u8g_font_u8glib_4.d \
./middleware/u8glib/fntsrc/u8g_font_u8glib_4r.d \
./middleware/u8glib/fntsrc/u8g_font_unifont.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_0_8.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_12_13.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_18_19.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_2_3.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_4_5.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_67_75.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_72_73.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_75r.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_76.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_77.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_78_79.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_86.d \
./middleware/u8glib/fntsrc/u8g_font_unifont_8_9.d \
./middleware/u8glib/fntsrc/u8g_font_unifontr.d 


# Each subdirectory must supply rules for building sources it contributes
middleware/u8glib/fntsrc/%.o: ../middleware/u8glib/fntsrc/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARC ELF32 GCC C Compiler'
	arc-elf32-gcc -mcpu=em -mlittle-endian -mmpy-option=0 -g3 -gdwarf-2 -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


