################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
arc \
arc/startup \
board \
board/emsk/common \
board/emsk/drivers/ip/designware/gpio \
board/emsk/drivers/ip/designware/iic \
board/emsk/drivers/ip/designware/spi \
board/emsk/drivers/ip/designware/uart \
board/emsk/drivers/mux \
board/emsk/drivers/ntshell \
board/emsk/drivers/pmwifi \
board/emsk/drivers/sdcard \
decadriver \
device/ip/designware/gpio \
device/ip/designware/iic \
device/ip/designware/sdio \
device/ip/designware/spi \
device/ip/designware/uart \
device/peripheral/802_15_4/mrf24j40 \
device/peripheral/adc/ad7991 \
device/peripheral/ble/hm1x \
device/peripheral/flash/w25qxx \
device/peripheral/sensor/temperature/adt7420 \
device/peripheral/sensor/temperature/tcn75 \
device/peripheral/wifi/mrf24g/driver \
device/peripheral/wifi/mrf24g \
device/peripheral/wifi/rw009 \
library/clib \
library/secureshield/board/emsk/common \
library/secureshield/board/nsim \
library/secureshield/core/src \
library/secureshield/core/src/v1 \
library/secureshield/core/src/v2 \
library/secureshield/export/src \
middleware/aws/external_libs/jsmn \
middleware/aws/platform/embARC/common \
middleware/aws/platform/embARC/freertos \
middleware/aws/platform/embARC/mbedtls \
middleware/aws/src \
middleware/coap \
middleware/common \
middleware/common/ringbuffer \
middleware/common/xprintf \
middleware/fatfs/doc/img \
middleware/fatfs/src/diskdrv \
middleware/fatfs/src \
middleware/fatfs/src/option \
middleware/http_parser/contrib \
middleware/http_parser \
middleware/ihex \
middleware/lwip/doc \
middleware/lwip/src/api \
middleware/lwip/src/apps/httpd \
middleware/lwip/src/apps/httpd/makefsdata \
middleware/lwip/src/apps/lwiperf \
middleware/lwip/src/apps/mdns \
middleware/lwip/src/apps/netbiosns \
middleware/lwip/src/apps/snmp \
middleware/lwip/src/apps/sntp \
middleware/lwip/src/apps/tftp \
middleware/lwip/src/core \
middleware/lwip/src/core/ipv4 \
middleware/lwip/src/core/ipv6 \
middleware/lwip/src/netif \
middleware/lwip/src/netif/ppp \
middleware/lwip/src/netif/ppp/polarssl \
middleware/lwip/test/unit/core \
middleware/lwip/test/unit/dhcp \
middleware/lwip/test/unit/etharp \
middleware/lwip/test/unit \
middleware/lwip/test/unit/mdns \
middleware/lwip/test/unit/tcp \
middleware/lwip/test/unit/udp \
middleware/lwip-contrib/Coverity \
middleware/lwip-contrib/apps/chargen \
middleware/lwip-contrib/apps/httpserver \
middleware/lwip-contrib/apps/netio \
middleware/lwip-contrib/apps/ping \
middleware/lwip-contrib/apps/rtp \
middleware/lwip-contrib/apps/shell \
middleware/lwip-contrib/apps/smtp \
middleware/lwip-contrib/apps/snmp_private_mib \
middleware/lwip-contrib/apps/socket_examples \
middleware/lwip-contrib/apps/tcpecho \
middleware/lwip-contrib/apps/tcpecho_raw \
middleware/lwip-contrib/apps/udpecho \
middleware/lwip-contrib/apps/udpecho_raw \
middleware/lwip-contrib/ports/arc \
middleware/lwip-contrib/ports/arc/netif \
middleware/lwip-contrib/ports/arc/sys_arch/baremetal \
middleware/lwip-contrib/ports/arc/sys_arch/freertos \
middleware/lwip-contrib/ports/old/6502 \
middleware/lwip-contrib/ports/old/c16x \
middleware/lwip-contrib/ports/old/c16x/netif \
middleware/lwip-contrib/ports/old/coldfire/netif \
middleware/lwip-contrib/ports/old/coldfire \
middleware/lwip-contrib/ports/old/ecos/ecos/net/lwip_tcpip/current/src/ecos \
middleware/lwip-contrib/ports/old/ecos/ecos/net/lwip_tcpip/current/tests \
middleware/lwip-contrib/ports/old/rtxc \
middleware/lwip-contrib/ports/old/rtxc/netif \
middleware/lwip-contrib/ports/old/ti_c6711 \
middleware/lwip-contrib/ports/old/ti_c6711/netif \
middleware/lwip-contrib/ports/old/ti_c6711/proj \
middleware/lwip-contrib/ports/old/v2pro \
middleware/lwip-contrib/ports/old/v2pro/netif \
middleware/lwip-contrib/ports/unix/fuzz \
middleware/lwip-contrib/ports/unix/lib \
middleware/lwip-contrib/ports/unix/minimal \
middleware/lwip-contrib/ports/unix/port/netif \
middleware/lwip-contrib/ports/unix/port \
middleware/lwip-contrib/ports/unix/unixsim \
middleware/lwip-contrib/ports/win32/check \
middleware/lwip-contrib/ports/win32 \
middleware/mbedtls/library \
middleware/mbedtls/programs/aes \
middleware/mbedtls/programs/hash \
middleware/mbedtls/programs/pkey \
middleware/mbedtls/programs/random \
middleware/mbedtls/programs/ssl \
middleware/mbedtls/programs/test \
middleware/mbedtls/programs/util \
middleware/mbedtls/programs \
middleware/mbedtls/programs/x509 \
middleware/mbedtls/yotta/data \
middleware/mbedtls/yotta/data/example-authcrypt \
middleware/mbedtls/yotta/data/example-benchmark \
middleware/mbedtls/yotta/data/example-hashing \
middleware/mbedtls/yotta/data/example-selftest \
middleware/mqtt/MQTTClient/src \
middleware/mqtt/MQTTClient/src/lwip \
middleware/mqtt/MQTTPacket/src \
middleware/ntshell/cmds \
middleware/ntshell/cmds/cmds_arc \
middleware/ntshell/cmds/cmds_extend \
middleware/ntshell/cmds/cmds_fs \
middleware/ntshell/cmds/cmds_fs/ymodem \
middleware/ntshell/cmds/cmds_peripheral \
middleware/ntshell/port \
middleware/ntshell/src \
middleware/openthread/mbedtls \
middleware/openthread/platforms/arc \
middleware/openthread/platforms/utils \
middleware/openthread/src/cli \
middleware/openthread/src/core/api \
middleware/openthread/src/core/coap \
middleware/openthread/src/core/common \
middleware/openthread/src/core/crypto \
middleware/openthread/src/core/mac \
middleware/openthread/src/core/meshcop \
middleware/openthread/src/core/net \
middleware/openthread/src/core/thread \
middleware/openthread/src/core/utils \
middleware/openthread/src/diag \
middleware/openthread/src/ncp \
middleware/parson \
middleware/parson/tests \
middleware/u8glib/csrc \
middleware/u8glib/fntsrc \
middleware/wakaama/core \
middleware/wakaama/core/er-coap-13 \
middleware/wakaama/port/conn/udp \
middleware/wakaama/port \
middleware/wakaama/tests/TLV \
middleware/wakaama/tests/bootstrap_server \
middleware/wakaama/tests/client \
middleware/wakaama/tests/lightclient \
middleware/wakaama/tests/misc \
middleware/wakaama/tests/server \
middleware/wakaama/tests/unittests \
middleware/wakaama/tests/utils \
platform \
. \

